services:
  - type: web
    name: line-calendar-bot
    env: python
    buildCommand: pip install --upgrade pip && pip install --no-cache-dir --force-reinstall gunicorn==21.2.0 && pip install -r requirements.txt && pip list | grep gunicorn
    startCommand: sh -c "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production 