services:
  - type: web
    name: line-calendar-bot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: .
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production 