services:
  - type: web
    name: line-calendar-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers=1 --timeout=300 --access-logfile=- --error-logfile=- --chdir=/opt/render/project/src app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src 