services:
  - type: web
    name: line-calendar-bot
    env: python
    buildCommand: pip install --upgrade pip && pip install --upgrade --force-reinstall -r requirements.txt
    startCommand: gunicorn app:app --worker-class eventlet --bind=0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production 